server:
  port: 8761

spring:
  application:
    name: sc-discovery

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}
  server:
    max-threads-for-peer-replication: 15
    max-time-for-replication: 30000