server:
  port: ${PORT_GATEWAY:9230}
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
    min-response-size: 1024
  servlet:
    encoding:
      force: true

spring:
  application:
    name: api-gateway
  main:
    allow-bean-definition-overriding: true
    log-startup-info: false

  jackson:
    default-property-inclusion: NON_NULL
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
  flyway:
    enabled: true
    table: schema-api-gateway
    out-of-order: true
    connect-retries: 3
    connect-retries-interval: 10
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${DATABASE_HOSTNAME:127.0.0.1}:${DATABASE_PORT:10432}/${GATEWAY_DATABASE:sc-gateway}
    username: ${DATABASE_USER:}
    password: ${DATABASE_PASSWORD:}
    hikari:
      pool-name: p:scaraz-gateway
      maximum-pool-size: 20
      connection-timeout: 60000
  jpa:
    database: POSTGRESQL
    show-sql: false
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.generate_statistics: true
      hibernate.jdbc.time_zone: Asia/Jakarta
#  webflux:
  cloud:
    gateway:
      loadbalancer:
        use404: true

scaraz:
  app:
    log-level: debug
    log-directory: ".logs"
    async:
      core-pool-size: 2
      max-pool-size: 50
      queue-capacity: 10_000
  gateway:
    host-profile: ${GATEWAY_HOST_PROFILE:production}