keycloak:
  enabled: true
  realm: ${KEYCLOAK_REALM:scaraz-dev}
  resource: api-gateway
  auth-server-url: ${KEYCLOAK_URL:https://auth.scaraz.dev}
  bearer-only: true

scaraz:
  gateway:
    host-profile: ALL