
scaraz:
  app:
    retrofit:
      log-level: BASIC
  gateway:
    core-svc-url: ${GATEWAY_CORE_URL:http://127.0.0.1:9231}
    kc-client-id: ${GATEWAY_CLIENT_ID:api-gateway}
    kc-client-secret: ${GATEWAY_CLIENT_SECRET:7JQpbZAud0CgEEHuGRSracFTHnyeNvdm}